-- Collective v7 one-file Supabase setup. Paste into Supabase SQL Editor and click Run.
create extension if not exists "pgcrypto";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, full_name text, bio text, current_goal text default 'speak-up', onboarding_completed boolean default false, default_visibility text default 'private', global_trust_level text default 'observer', is_admin boolean default false, created_at timestamptz default now());
create table if not exists public.paths (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, description text not null, category text not null, difficulty text default 'beginner', estimated_days int default 14, is_active boolean default true, created_at timestamptz default now());
create table if not exists public.prompts (id uuid primary key default gen_random_uuid(), path_id uuid not null references public.paths(id) on delete cascade, title text not null, instruction text not null, proof_type text not null, reflection_question text not null, feedback_question text, order_index int not null, estimated_minutes int default 5, is_active boolean default true, created_at timestamptz default now());
create table if not exists public.proof_submissions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, path_id uuid references public.paths(id), prompt_id uuid references public.prompts(id), proof_type text default 'text', text_response text, media_url text, reflection text not null, feedback_request text, visibility text default 'private', status text default 'submitted', created_at timestamptz default now());
create table if not exists public.feedback (id uuid primary key default gen_random_uuid(), proof_submission_id uuid not null references public.proof_submissions(id) on delete cascade, giver_id uuid references public.profiles(id), feedback_type text default 'peer', what_worked text not null, what_could_improve text, next_step text not null, usefulness_rating int, created_at timestamptz default now());
create table if not exists public.trust_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), event_type text not null, score_change numeric default 0, reason text, created_at timestamptz default now());
create table if not exists public.feed_items (id uuid primary key default gen_random_uuid(), type text not null, mode text not null default 'passive', path_slug text, title text not null, body text not null, action_label text, action_href text, usefulness int default 50, actionability int default 50, proof_strength int default 50, trust_weight int default 50, recency int default 50, friction int default 20, is_active boolean default true, created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.paths enable row level security; alter table public.prompts enable row level security; alter table public.proof_submissions enable row level security; alter table public.feedback enable row level security; alter table public.trust_events enable row level security; alter table public.feed_items enable row level security;
create policy if not exists "read active paths" on public.paths for select using (is_active=true);
create policy if not exists "read active prompts" on public.prompts for select using (is_active=true);
create policy if not exists "read active feed" on public.feed_items for select using (is_active=true);
create policy if not exists "own profile" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy if not exists "own proof" on public.proof_submissions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
insert into public.paths (slug,title,description,category) values ('speak-up','Speak Up','Build confidence and communicate clearly.','communication'),('social-momentum','Social Momentum','Build connection through small social actions.','connection'),('daily-momentum','Daily Momentum','Build consistency through tiny useful actions.','momentum'),('give-better-feedback','Give Better Feedback','Learn to help others with specific feedback.','contribution') on conflict (slug) do nothing;
