import type { FeedItem, GrowthPath, PracticePrompt } from "./types";
export const paths: GrowthPath[] = [
 { slug:"speak-up", title:"Speak Up", description:"Build confidence and communicate clearly.", promise:"Practice direct, respectful expression in small steps.", color:"from-orange-400 to-orange-600", estimatedDays:14 },
 { slug:"social-momentum", title:"Social Momentum", description:"Build connection through small social actions.", promise:"Stop waiting to feel ready and practice reaching out.", color:"from-green-400 to-emerald-600", estimatedDays:14 },
 { slug:"daily-momentum", title:"Daily Momentum", description:"Build consistency through tiny useful actions.", promise:"Turn stuck energy into visible progress.", color:"from-blue-400 to-indigo-600", estimatedDays:14 },
 { slug:"give-better-feedback", title:"Give Better Feedback", description:"Learn to help others with specific feedback.", promise:"Become useful without pretending to be an expert.", color:"from-purple-400 to-fuchsia-600", estimatedDays:7 }
];
export const prompts: PracticePrompt[] = [
 { id:"speak-up-1", pathSlug:"speak-up", title:"One Honest Sentence", instruction:"Write one sentence you would say if you were being honest but respectful.", proofType:"text", reflectionQuestion:"What made this hard to say?", feedbackQuestion:"Do you want feedback on clarity, tone, or courage?", estimatedMinutes:5, order:1 },
 { id:"speak-up-2", pathSlug:"speak-up", title:"One Clear Preference", instruction:"Name one preference today without apologizing for having it.", proofType:"text", reflectionQuestion:"Where did you soften the statement?", feedbackQuestion:"Was the preference clear and respectful?", estimatedMinutes:5, order:2 },
 { id:"speak-up-3", pathSlug:"speak-up", title:"Ask Directly", instruction:"Write one clear ask with a specific action and timeline.", proofType:"text", reflectionQuestion:"What part of being direct feels risky?", feedbackQuestion:"Is the ask specific enough?", estimatedMinutes:7, order:3 },
 { id:"social-1", pathSlug:"social-momentum", title:"Thoughtful Message", instruction:"Send or draft one thoughtful message to someone you have been meaning to reach out to.", proofType:"text", reflectionQuestion:"What made you choose this person?", feedbackQuestion:"Does the message feel warm and low-pressure?", estimatedMinutes:8, order:1 },
 { id:"momentum-1", pathSlug:"daily-momentum", title:"Five-Minute Useful Step", instruction:"Choose one five-minute action that would make today slightly better and do it.", proofType:"checklist", reflectionQuestion:"What made this action small enough to start?", feedbackQuestion:"What should your next smallest step be?", estimatedMinutes:5, order:1 },
 { id:"feedback-1", pathSlug:"give-better-feedback", title:"Specific, Not Vague", instruction:"Turn vague praise into specific feedback using what worked, why it worked, and one next step.", proofType:"text", reflectionQuestion:"What changed when the feedback became specific?", feedbackQuestion:"Is this feedback useful without being harsh?", estimatedMinutes:8, order:1 }
];
export const demoFeedItems: FeedItem[] = [
 { id:"f1", type:"reflection", mode:"passive", actor:"Maya", title:"I realized I soften every request with maybe.", body:"Maya completed One Honest Sentence and noticed she makes every ask sound optional.", pathSlug:"speak-up", trustSignal:"Participant - 3 proofs", actionLabel:"Try this practice", actionHref:"/practice/speak-up-1", usefulness:85, actionability:80, proofStrength:75, trustWeight:55, recency:92, friction:20 },
 { id:"f2", type:"prompt", mode:"active", title:"Your next 5-minute practice", body:"Write one honest sentence you would say if you were being direct and respectful. Keep it private.", pathSlug:"speak-up", actionLabel:"Start now", actionHref:"/practice/speak-up-1", usefulness:96, actionability:100, proofStrength:65, trustWeight:70, recency:88, friction:10 },
 { id:"f3", type:"feedback", mode:"bridge", actor:"Ava", title:"Good feedback is specific enough to act on.", body:"Instead of saying great job, name what worked and one next step.", pathSlug:"give-better-feedback", trustSignal:"Trusted Contributor", actionLabel:"Practice feedback", actionHref:"/contribute", usefulness:92, actionability:82, proofStrength:78, trustWeight:90, recency:75, friction:25 },
 { id:"f4", type:"milestone", mode:"passive", actor:"Jordan", title:"Jordan hit 7 days of Daily Momentum.", body:"The pattern was not huge effort. It was one small action before checking distractions.", pathSlug:"daily-momentum", trustSignal:"7-day streak", actionLabel:"Try a 5-minute step", actionHref:"/practice/momentum-1", usefulness:76, actionability:70, proofStrength:82, trustWeight:58, recency:80, friction:15 },
 { id:"f5", type:"question", mode:"bridge", title:"What are you avoiding saying clearly?", body:"You do not have to send it yet. Draft the sentence privately first. The first win is clarity.", pathSlug:"speak-up", actionLabel:"Draft privately", actionHref:"/practice/speak-up-1", usefulness:88, actionability:92, proofStrength:55, trustWeight:64, recency:86, friction:5 },
 { id:"f6", type:"contribution", mode:"active", title:"3 proof posts need kind feedback.", body:"Help someone by naming one thing that worked and one next step. The template keeps it safe.", pathSlug:"give-better-feedback", actionLabel:"Open Contribution Hub", actionHref:"/contribute", usefulness:83, actionability:95, proofStrength:70, trustWeight:76, recency:95, friction:35 }
];
export function getPath(slug: string) { return paths.find(p => p.slug === slug); }
export function getPrompt(id: string) { return prompts.find(p => p.id === id); }
export function getFirstPromptForPath(pathSlug: string) { return prompts.find(p => p.pathSlug === pathSlug && p.order === 1) || prompts[0]; }
